In [25]:
from your_student_id import *
from pathlib import Path

In [26]:
engine = STLOS_Engine(Path("test_data/tier_1"), cost_per_liter=7.5, tax_multiplier=0.1)

In [27]:
spec_path = list(engine.root.rglob("specs.json"))[0]
engine._parse_specs(spec_path)

{'model': 'Electric-X', 'tank_capacity': 100.0, 'carbon_rate': 0.05}

In [28]:
t_path = spec_path.parent / "telemetry.csv"
engine._load_telemetry(t_path)

             timestamp        lat         lon  fuel_level
0  2024-01-01 00:00:00  22.499919  113.900525   99.920537
1  2024-01-01 00:01:00  22.500013  113.900616   99.451167
2  2024-01-01 00:02:00  22.499916  113.901465   98.252976
3  2024-01-01 00:03:00  22.500064  113.901071   97.848334
4  2024-01-01 00:04:00  22.499456  113.901427   97.396418
..                 ...        ...         ...         ...
95 2024-01-01 01:35:00  22.493656  113.900527   32.852795
96 2024-01-01 01:36:00  22.493656  113.900197   32.023648
97 2024-01-01 01:37:00  22.494043  113.900179   31.464268
98 2024-01-01 01:38:00  22.494116  113.900218   30.771609
99 2024-01-01 01:39:00  22.493499  113.901186   29.944393

[100 rows x 4 columns]

In [29]:
engine.ingest_fleet_data()
engine.fleet

{'Baoan/VEH-1000': <your_student_id.Vehicle at 0x25c3e6d0f10>,
 'Baoan/VEH-1001': <your_student_id.Vehicle at 0x25c3e6ec7d0>,
 'Baoan/VEH-1002': <your_student_id.Vehicle at 0x25c3e771e10>,
 'Baoan/VEH-1003': <your_student_id.Vehicle at 0x25c3e773f90>,
 'Baoan/VEH-1004': <your_student_id.Vehicle at 0x25c3e6edb90>,
 'Futian/VEH-1000': <your_student_id.Vehicle at 0x25c3e72cdd0>,
 'Futian/VEH-1001': <your_student_id.Vehicle at 0x25c3e75d610>,
 'Futian/VEH-1002': <your_student_id.Vehicle at 0x25c3e75fd90>,
 'Futian/VEH-1003': <your_student_id.Vehicle at 0x25c3e6d0450>,
 'Futian/VEH-1004': <your_student_id.Vehicle at 0x25c3e773ad0>,
 'Longgang/VEH-1000': <your_student_id.Vehicle at 0x25c3e75e0d0>,
 'Longgang/VEH-1001': <your_student_id.Vehicle at 0x25c3e76abd0>,
 'Longgang/VEH-1002': <your_student_id.Vehicle at 0x25c3e764f90>,
 'Longgang/VEH-1003': <your_student_id.Vehicle at 0x25c3e767b10>,
 'Longgang/VEH-1004': <your_student_id.Vehicle at 0x25c3e766310>,
 'Nanshan/VEH-1000': <your_student_id.Vehicle at 0x25c3e76b6d0>,
 'Nanshan/VEH-1001': <your_student_id.Vehicle at 0x25c3e72d190>,
 'Nanshan/VEH-1002': <your_student_id.Vehicle at 0x25c3e7527d0>,
 'Nanshan/VEH-1003': <your_student_id.Vehicle at 0x25c3e683fd0>,
 'Nanshan/VEH-1004': <your_student_id.Vehicle at 0x25c3e751710>}

In [30]:
engine.merge_districts()
engine.master_telemetry

,timestamp,lat,lon,fuel_level,district,vehicle_key,v_id,fleet_key,carbon_rate
0,2024-01-01 00:00:00,22.499919,113.900525,99.920537,Baoan,Baoan/VEH-1000,VEH-1000,Baoan/VEH-1000,0.05
1,2024-01-01 00:01:00,22.500013,113.900616,99.451167,Baoan,Baoan/VEH-1000,VEH-1000,Baoan/VEH-1000,0.05
2,2024-01-01 00:02:00,22.499916,113.901465,98.252976,Baoan,Baoan/VEH-1000,VEH-1000,Baoan/VEH-1000,0.05
3,2024-01-01 00:03:00,22.500064,113.901071,97.848334,Baoan,Baoan/VEH-1000,VEH-1000,Baoan/VEH-1000,0.05
4,2024-01-01 00:04:00,22.499456,113.901427,97.396418,Baoan,Baoan/VEH-1000,VEH-1000,Baoan/VEH-1000,0.05
...,...,...,...,...,...,...,...,...,...
1990,2024-01-01 01:35:00,22.502308,113.902866,32.799151,Nanshan,Nanshan/VEH-1004,VEH-1004,Nanshan/VEH-1004,0.05
1991,2024-01-01 01:36:00,22.502128,113.902965,32.102211,Nanshan,Nanshan/VEH-1004,VEH-1004,Nanshan/VEH-1004,0.05
1992,2024-01-01 01:37:00,22.501964,113.902875,31.109879,Nanshan,Nanshan/VEH-1004,VEH-1004,Nanshan/VEH-1004,0.05
1993,2024-01-01 01:38:00,22.501422,113.903153,30.777213,Nanshan,Nanshan/VEH-1004,VEH-1004,Nanshan/VEH-1004,0.05
1994,2024-01-01 01:39:00,22.500880,113.903431,29.830498,Nanshan,Nanshan/VEH-1004,VEH-1004,Nanshan/VEH-1004,0.05

In [31]:
engine.calculate_velocity_vector('VEH-1000')

array([0.16913499, 1.05371782, 0.52378118, 0.92215696, 0.79498774,
       0.96778194, 0.97477579, 0.28229532, 0.58068049, 0.55247513,
       0.55247551, 1.07809116, 0.99566238, 0.6306    , 0.90246994,
       0.93720396, 0.74214967, 0.62038701, 0.70121591, 0.57304702,
       0.8095199 , 0.63440215, 1.12107137, 0.78982392, 0.72221668,
       0.78201007, 0.42568534, 1.31225709, 0.63418935, 0.55102824,
       0.511094  , 0.88320925, 0.90321741, 0.71569297, 0.52569898,
       0.43267604, 0.90040587, 0.11436355, 0.11436353, 1.23400599,
       1.33691155, 0.45351404, 1.40621105, 0.55145394, 0.74880856,
       1.63578269, 1.01523799, 0.91945891, 0.85001086, 0.87797084,
       0.32425901, 0.42710349, 1.2807206 , 0.77799773, 0.7779986 ,
       1.32035508, 0.92648465, 0.39903572, 0.57357741, 0.56260043,
       0.3780466 , 0.37804689, 0.36678497, 0.65391946, 0.6902002 ,
       0.87798299, 0.95558098, 0.70728374, 0.9615014 , 1.16827554,
       0.15745769, 1.54217946, 0.88015333, 0.39235971, 0.39839433,
       0.9866126 , 1.0561943 , 0.6202133 , 0.26540077, 0.38350132,
       0.85568605, 1.14659012, 0.97797311, 0.21113855, 0.29219452,
       0.47010416, 0.72365537, 0.75755856, 0.82966228, 0.94183188,
       1.21254026, 0.4741691 , 0.47416873, 0.67330125, 1.47661656,
       0.40713496, 0.51694578, 0.10925585, 1.45084122])

In [32]:
engine.detect_idling_events()

Empty DataFrame
Columns: [timestamp, lat, lon, fuel_level, district, vehicle_key, v_id, fleet_key, carbon_rate, is_idling]
Index: []

In [33]:
engine.compute_fuel_burn_rate()

,timestamp,lat,lon,fuel_level,district,vehicle_key,v_id,fleet_key,carbon_rate,is_idling,dist_delta,fuel_delta,burn_rate
0,2024-01-01 00:00:00,22.499919,113.900525,99.920537,Baoan,Baoan/VEH-1000,VEH-1000,Baoan/VEH-1000,0.05,False,0.000000,0.000000,0.000000
1,2024-01-01 00:01:00,22.500013,113.900616,99.451167,Baoan,Baoan/VEH-1000,VEH-1000,Baoan/VEH-1000,0.05,False,0.014095,0.469370,33.301429
2,2024-01-01 00:02:00,22.499916,113.901465,98.252976,Baoan,Baoan/VEH-1000,VEH-1000,Baoan/VEH-1000,0.05,False,0.087810,1.198191,13.645296
3,2024-01-01 00:03:00,22.500064,113.901071,97.848334,Baoan,Baoan/VEH-1000,VEH-1000,Baoan/VEH-1000,0.05,False,0.043648,0.404642,9.270482
4,2024-01-01 00:04:00,22.499456,113.901427,97.396418,Baoan,Baoan/VEH-1000,VEH-1000,Baoan/VEH-1000,0.05,False,0.076846,0.451916,5.880766
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1990,2024-01-01 01:35:00,22.502308,113.902866,32.799151,Nanshan,Nanshan/VEH-1004,VEH-1004,Nanshan/VEH-1004,0.05,False,0.086935,0.965326,11.104058
1991,2024-01-01 01:36:00,22.502128,113.902965,32.102211,Nanshan,Nanshan/VEH-1004,VEH-1004,Nanshan/VEH-1004,0.05,False,0.022477,0.696940,31.007470
1992,2024-01-01 01:37:00,22.501964,113.902875,31.109879,Nanshan,Nanshan/VEH-1004,VEH-1004,Nanshan/VEH-1004,0.05,False,0.020406,0.992333,48.629318
1993,2024-01-01 01:38:00,22.501422,113.903153,30.777213,Nanshan,Nanshan/VEH-1004,VEH-1004,Nanshan/VEH-1004,0.05,False,0.066687,0.332666,4.988476
1994,2024-01-01 01:39:00,22.500880,113.903431,29.830498,Nanshan,Nanshan/VEH-1004,VEH-1004,Nanshan/VEH-1004,0.05,False,0.066687,0.946715,14.196422

In [34]:
engine.find_nearest_refuel_station('./test_data/tier_1/refuel_stations.csv')

             fleet_key           timestamp  nearest_station_idx
0       Baoan/VEH-1000 2024-01-01 00:00:00                    0
1       Baoan/VEH-1000 2024-01-01 00:01:00                    0
2       Baoan/VEH-1000 2024-01-01 00:02:00                    0
3       Baoan/VEH-1000 2024-01-01 00:03:00                    0
4       Baoan/VEH-1000 2024-01-01 00:04:00                    0
...                ...                 ...                  ...
1990  Nanshan/VEH-1004 2024-01-01 01:35:00                    0
1991  Nanshan/VEH-1004 2024-01-01 01:36:00                    0
1992  Nanshan/VEH-1004 2024-01-01 01:37:00                    0
1993  Nanshan/VEH-1004 2024-01-01 01:38:00                    0
1994  Nanshan/VEH-1004 2024-01-01 01:39:00                    0

[1995 rows x 3 columns]

In [35]:
engine.calculate_fleet_carbon_tax()

1.5202455022976857

In [36]:
engine.generate_district_report()

          mean_fuel_level
district
Baoan           64.986334
Futian          64.844706
Longgang        64.929302
Nanshan         64.861591